# Generated by Django 6.1.1 on 2026-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='capa',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
