# Generated by Django 6.1.1 on 2026-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_manga_capa_manga_descricao_manga_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='manga',
            name='genero',
        ),
        migrations.AddField(
            model_name='manga',
            name='genero',
            field=models.ManyToManyField(blank=True, to='mangas.genero'),
        ),
    ]
