# Generated by Django 6.1.1 on 2026-09-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_genero_remove_manga_genero_manga_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='genero',
            new_name='generos',
        ),
    ]
